// constants/subcategories.js
export const SUBCATEGORIES = {
  JEWELRY: [
    "NECKLACES",
    "EARRINGS",
    "BRACELETS",
    "RINGS",
    "CRYSTAL COLLECTION",
    "PEARL COLLECTION",
    "STATEMENT PIECES",
    "MINIMALIST",
    "GOLD PLATED",
    "SILVER PLATED",
    "ROSE GOLD",
    "GEMSTONES",
  ],
  COATS: [
    "OVERCOATS",
    "TRENCH COATS",
    "PUFFER JACKETS",
    "PARKAS",
    "WOOL",
    "LEATHER",
    "COTTON",
    "SYNTHETIC",
  ],
  KIDS_CLOTHING: [
    "TOPS",
    "BOTTOMS",
    "DRESSES",
    "OUTERWEAR",
    "BABY (0-2 YEARS)",
    "TODDLER (2-4 YEARS)",
    "LITTLE KIDS (4-7 YEARS)",
    "BIG KIDS (8-12 YEARS)",
    "CASUAL",
    "FORMAL",
    "SCHOOL",
    "SEASONAL",
  ],
};